### PR TITLE
[Auth] Turn it into a flask application

### PR DESCRIPTION
**Pull request by paiva**
This PR:
* Takes the login html code and turns it into a flask application
* This application will work with `conp-portal` to authenticate and whitelist users
* Edit: It is missing a couple of links below the card, such as "register" and "go back to CONP Portal". Will be added in a different PR

screen shot 2019-03-05 at 11 21 10 am

### CODE REVIEW

**Comment by jbpoline** [comment]
Santiago: Looks good to me but I did not do a proper review - lmk if you want a deep review and I wont merge - if not, I will

**Comment by DESm1th** [comment]
Looks beautiful on chrome but firefox seems to mangle everything. **Edit: I think this may have been a CDN related hiccup. Everything seems fine and firefox started rendering the same as chrome after a few minutes 
screenshot from 2019-03-05 12-38-35

**Comment by paiva** [comment]
@DESm1th Which version of Firefox where you using? Works fine on v 65.0.1
screen shot 2019-03-05 at 2 32 36 pm

**Comment by paiva** [comment]
@jbpoline We are testing on different browsers. If everything works, you can merge it.

**Comment by DESm1th** [comment]
It was 65.0.1, but it resolved itself. I think it may have been a networking hiccup / CAMH's firewall preventing the CDN copy of bootstrap from being pulled in for a few minutes. Sorry for the false alarm! It seems to work on our end now too.

**Comment by jbpoline** [comment]
cool

**Pull request merged**
